# Generated by Django 5.0.2 on 2025-05-19 12:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_default_variant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeValuePriceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='price_adjustments', to='products.attributevalue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attribute_price_adjustments', to='products.product')),
            ],
            options={
                'db_table': 'attributevaluepriceadjustment',
                'managed': True,
                'unique_together': {('attribute_value', 'product')},
            },
        ),
    ]
