# Generated by Django 5.0.2 on 2025-05-19 12:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_attributevaluepriceadjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('required', models.BooleanField(default=False)),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.attributevalue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_attributes', to='products.product')),
            ],
            options={
                'db_table': 'productattribute',
                'managed': True,
                'unique_together': {('product', 'attribute_value')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(related_name='products', through='products.ProductAttribute', to='products.attributevalue'),
        ),
    ]
