# Generated by Django 5.0.2 on 2025-05-19 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productattribute_product_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
    ]
