# Generated by Django 5.0.2 on 2025-05-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_attributes_delete_productattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='attribute_values',
            field=models.ManyToManyField(related_name='variants', to='products.attributevalue'),
        ),
    ]
