# Generated by Django 5.0.2 on 2025-06-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_attributetype_created_by_attributetype_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price_adjustment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
    ]
