# Generated by Django 5.0.2 on 2025-07-02 08:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_alter_product_base_price_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="variantimage",
            options={"managed": True, "ordering": ["display_order", "id"]},
        ),
        migrations.AddField(
            model_name="productvariant",
            name="dimensions",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="variantimage",
            name="display_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="variantimage",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together={("product", "sku")},
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["product"], name="productvari_product_40111c_idx"
            ),
        ),
    ]
