# Generated by Django 5.0.2 on 2025-07-04 07:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0012_alter_variantimage_options_productvariant_dimensions_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="warranty_period",
            field=models.IntegerField(
                blank=True,
                help_text="Thời gian bảo hành theo tháng. Nếu để trống sẽ lấy từ product",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["warranty_period"], name="productvari_warrant_6a24ec_idx"
            ),
        ),
    ]
