# Generated by Django 5.0.2 on 2025-07-07 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productvariant_warranty_period_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariantAttribute',
        ),
    ]
