-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.attributetype
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_deleted boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT attributetype_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.attributevalue
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_deleted boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    value character varying(255) COLLATE pg_catalog."default" NOT NULL,
    attribute_type_id bigint,
    CONSTRAINT attributevalue_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.audit_log
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_deleted boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    action character varying(10) COLLATE pg_catalog."default" NOT NULL,
    model_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    object_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    old_values jsonb,
    new_values jsonb,
    ip_address inet,
    action_date timestamp with time zone NOT NULL,
    user_id bigint,
    CONSTRAINT audit_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.auth_group
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_group_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.auth_group_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.auth_permission
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
    CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename)
);

CREATE TABLE IF NOT EXISTS public.banner
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_deleted boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    image_url character varying(255) COLLATE pg_catalog."default" NOT NULL,
    link_url character varying(255) COLLATE pg_catalog."default",
    alt_text character varying(255) COLLATE pg_catalog."default",
    start_date timestamp with time zone,
    end_date timestamp with time zone,
    display_order integer,
    is_active boolean,
    banner_location character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_by bigint,
    updated_by bigint,
    CONSTRAINT banner_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.brand
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_deleted boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    logo_url character varying(255) COLLATE pg_catalog."default",
    display_order integer,
    slug character varying(255) COLLATE pg_catalog."default",
    meta_title character varying(255) COLLATE pg_catalog."default",
    meta_description text COLLATE pg_catalog."default",
    is_active boolean,
    created_by bigint,
    updated_by bigint,
    CONSTRAINT brand_pkey PRIMARY KEY (id),
    CONSTRAINT brand_slug_key UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.category
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_deleted boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    display_order integer,
    slug character varying(255) COLLATE pg_catalog."default",
    meta_title character varying(255) COLLATE pg_catalog."default",
    meta_description text COLLATE pg_catalog."default",
    is_active boolean,
    created_by bigint,
    parent_id bigint,
    updated_by bigint,
    CONSTRAINT category_pkey PRIMARY KEY (id),
    CONSTRAINT category_slug_key UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.contactinfo
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_deleted boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    company_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    address text COLLATE pg_catalog."default",
    phone character varying(20) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    working_hours text COLLATE pg_catalog."default",
    facebook_url character varying(255) COLLATE pg_catalog."default",
    instagram_url character varying(255) COLLATE pg_catalog."default",
    youtube_url character varying(255) COLLATE pg_catalog."default",
    tiktok_url character varying(255) COLLATE pg_catalog."default",
    is_active boolean,
    created_by bigint,
    updated_by bigint,
    CONSTRAINT contactinfo_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.coupon
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_deleted boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    discount_type character varying(20) COLLATE pg_catalog."default",
    discount_value numeric(10, 2) NOT NULL,
    minimum_order_amount numeric(10, 2),
    starts_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    usage_limit integer,
    usage_count integer,
    is_active boolean,
    created_by bigint,
    updated_by bigint,
    CONSTRAINT coupon_pkey PRIMARY KEY (id),
    CONSTRAINT coupon_code_key UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.django_admin_log
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    action_time timestamp with time zone NOT NULL,
    object_id text COLLATE pg_catalog."default",
    object_repr character varying(200) COLLATE pg_catalog."default" NOT NULL,
    action_flag smallint NOT NULL,
    change_message text COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_content_type
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    app_label character varying(100) COLLATE pg_catalog."default" NOT NULL,
    model character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_content_type_pkey PRIMARY KEY (id),
    CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model)
);

CREATE TABLE IF NOT EXISTS public.django_migrations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    app character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    applied timestamp with time zone NOT NULL,
    CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_session
(
    session_key character varying(40) COLLATE pg_catalog."default" NOT NULL,
    session_data text COLLATE pg_catalog."default" NOT NULL,
    expire_date timestamp with time zone NOT NULL,
    CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);

CREATE TABLE IF NOT EXISTS public.employee
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_deleted boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(20) COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    employee_code character varying(50) COLLATE pg_catalog."default",
    "position" character varying(100) COLLATE pg_catalog."default",
    hire_date date,
    user_id bigint,
    store_id bigint,
    CONSTRAINT employee_pkey PRIMARY KEY (id),
    CONSTRAINT employee_employee_code_key UNIQUE (employee_code)
);

CREATE TABLE IF NOT EXISTS public.footercategory
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_deleted boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    display_order integer,
    is_active boolean,
    created_by bigint,
    updated_by bigint,
    CONSTRAINT footercategory_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.footerlink
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_deleted boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    url character varying(255) COLLATE pg_catalog."default" NOT NULL,
    display_order integer,
    is_active boolean,
    category_id bigint,
    created_by bigint,
    updated_by bigint,
    CONSTRAINT footerlink_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.inventory
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_deleted boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    quantity integer,
    last_updated timestamp with time zone,
    product_variant_id bigint,
    store_id bigint,
    CONSTRAINT inventory_pkey PRIMARY KEY (id),
    CONSTRAINT inventory_product_variant_id_store_id_a496cd2a_uniq UNIQUE (product_variant_id, store_id)
);

CREATE TABLE IF NOT EXISTS public.inventorytransaction
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_deleted boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    transaction_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(10, 2),
    reference_id integer,
    reference_type character varying(50) COLLATE pg_catalog."default",
    note text COLLATE pg_catalog."default",
    transaction_date timestamp with time zone,
    created_by bigint,
    inventory_id bigint,
    updated_by bigint,
    CONSTRAINT inventorytransaction_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.news
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_deleted boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    slug character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content text COLLATE pg_catalog."default",
    summary text COLLATE pg_catalog."default",
    featured_image character varying(255) COLLATE pg_catalog."default",
    is_published boolean,
    publish_date timestamp with time zone,
    meta_title character varying(255) COLLATE pg_catalog."default",
    meta_description text COLLATE pg_catalog."default",
    view_count integer,
    created_by bigint,
    updated_by bigint,
    category_id bigint,
    CONSTRAINT news_pkey PRIMARY KEY (id),
    CONSTRAINT news_slug_key UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.newscategory
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_deleted boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    slug character varying(150) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    display_order integer,
    is_active boolean,
    created_by bigint,
    updated_by bigint,
    CONSTRAINT newscategory_pkey PRIMARY KEY (id),
    CONSTRAINT newscategory_slug_key UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.orderdetail
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_deleted boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    quantity integer NOT NULL,
    unit_price numeric(10, 2) NOT NULL,
    discount numeric(10, 2),
    product_variant_id bigint,
    order_id bigint,
    CONSTRAINT orderdetail_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_deleted boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    order_date timestamp with time zone,
    status character varying(50) COLLATE pg_catalog."default",
    payment_method character varying(50) COLLATE pg_catalog."default",
    payment_status character varying(50) COLLATE pg_catalog."default",
    shipping_address text COLLATE pg_catalog."default",
    shipping_method character varying(100) COLLATE pg_catalog."default",
    tracking_number character varying(100) COLLATE pg_catalog."default",
    subtotal numeric(10, 2) NOT NULL,
    tax numeric(10, 2),
    shipping_fee numeric(10, 2),
    discount numeric(10, 2),
    total_amount numeric(10, 2) NOT NULL,
    note text COLLATE pg_catalog."default",
    is_online_order boolean,
    created_by bigint,
    customer_id bigint,
    employee_id bigint,
    store_id bigint,
    updated_by bigint,
    CONSTRAINT orders_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.orders_customer
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default",
    phone character varying(20) COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    birth_date date,
    gender character varying(10) COLLATE pg_catalog."default",
    notes text COLLATE pg_catalog."default",
    is_deleted boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id bigint,
    updated_by_id bigint,
    CONSTRAINT orders_customer_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_deleted boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    base_price numeric(10, 2) NOT NULL,
    warranty_period integer,
    slug character varying(255) COLLATE pg_catalog."default",
    meta_title character varying(255) COLLATE pg_catalog."default",
    meta_description text COLLATE pg_catalog."default",
    is_featured boolean,
    is_active boolean,
    brand_id bigint,
    category_id bigint,
    created_by bigint,
    updated_by bigint,
    CONSTRAINT product_pkey PRIMARY KEY (id),
    CONSTRAINT product_slug_key UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.productimage
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_deleted boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    is_primary boolean NOT NULL,
    alt_text character varying(255) COLLATE pg_catalog."default",
    display_order integer,
    created_by bigint,
    product_id bigint,
    updated_by bigint,
    product_variant_id bigint,
    image character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT productimage_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.productvariant
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_deleted boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    sku character varying(100) COLLATE pg_catalog."default" NOT NULL,
    price_adjustment numeric(10, 2),
    stock_alert_threshold integer,
    barcode character varying(100) COLLATE pg_catalog."default",
    is_active boolean,
    created_by bigint,
    product_id bigint,
    updated_by bigint,
    CONSTRAINT productvariant_pkey PRIMARY KEY (id),
    CONSTRAINT productvariant_sku_key UNIQUE (sku)
);

CREATE TABLE IF NOT EXISTS public.productvariantattribute
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_deleted boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    attribute_value_id bigint,
    product_variant_id bigint,
    CONSTRAINT productvariantattribute_pkey PRIMARY KEY (id),
    CONSTRAINT productvariantattribute_product_variant_id_attri_ca93d4da_uniq UNIQUE (product_variant_id, attribute_value_id)
);

CREATE TABLE IF NOT EXISTS public.returnorder
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_deleted boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    return_date timestamp with time zone,
    reason text COLLATE pg_catalog."default",
    status character varying(50) COLLATE pg_catalog."default",
    refund_amount numeric(10, 2),
    refund_method character varying(50) COLLATE pg_catalog."default",
    refund_status character varying(50) COLLATE pg_catalog."default",
    created_by bigint,
    customer_id bigint,
    order_id bigint,
    updated_by bigint,
    CONSTRAINT returnorder_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.returnorderdetail
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_deleted boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    quantity integer NOT NULL,
    reason text COLLATE pg_catalog."default",
    condition character varying(50) COLLATE pg_catalog."default",
    order_detail_id bigint,
    product_variant_id bigint,
    return_order_id bigint,
    CONSTRAINT returnorderdetail_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.stocktake
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_deleted boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    start_date timestamp with time zone,
    end_date timestamp with time zone,
    status character varying(50) COLLATE pg_catalog."default",
    notes text COLLATE pg_catalog."default",
    created_by bigint,
    store_id bigint,
    updated_by bigint,
    CONSTRAINT stocktake_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.stocktakedetail
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_deleted boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    expected_quantity integer,
    actual_quantity integer,
    discrepancy integer,
    notes text COLLATE pg_catalog."default",
    product_variant_id bigint,
    stock_take_id bigint,
    CONSTRAINT stocktakedetail_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.stocktransfer
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_deleted boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    transfer_date timestamp with time zone,
    status character varying(50) COLLATE pg_catalog."default",
    note text COLLATE pg_catalog."default",
    created_by bigint,
    destination_store_id bigint,
    source_store_id bigint,
    updated_by bigint,
    CONSTRAINT stocktransfer_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.stocktransferdetail
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_deleted boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    quantity integer NOT NULL,
    received_quantity integer,
    product_variant_id bigint,
    stock_transfer_id bigint,
    CONSTRAINT stocktransferdetail_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.store
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_deleted boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    address text COLLATE pg_catalog."default" NOT NULL,
    phone character varying(20) COLLATE pg_catalog."default",
    store_code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    opening_date date,
    is_active boolean,
    created_by bigint,
    manager_id bigint,
    updated_by bigint,
    CONSTRAINT store_pkey PRIMARY KEY (id),
    CONSTRAINT store_store_code_key UNIQUE (store_code)
);

CREATE TABLE IF NOT EXISTS public.supplier
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_deleted boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    contact_person character varying(100) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    phone character varying(20) COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    tax_code character varying(50) COLLATE pg_catalog."default",
    website character varying(255) COLLATE pg_catalog."default",
    is_active boolean,
    created_by bigint,
    updated_by bigint,
    CONSTRAINT supplier_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.useraccount
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    password character varying(128) COLLATE pg_catalog."default" NOT NULL,
    is_superuser boolean NOT NULL,
    username character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default",
    last_login timestamp with time zone,
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL,
    failed_login_attempts integer NOT NULL,
    account_locked_until timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT useraccount_pkey PRIMARY KEY (id),
    CONSTRAINT useraccount_email_key UNIQUE (email),
    CONSTRAINT useraccount_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.useraccount_groups
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    useraccount_id bigint NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT useraccount_groups_pkey PRIMARY KEY (id),
    CONSTRAINT useraccount_groups_useraccount_id_group_id_96359b67_uniq UNIQUE (useraccount_id, group_id)
);

CREATE TABLE IF NOT EXISTS public.useraccount_user_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    useraccount_id bigint NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT useraccount_user_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT useraccount_user_permiss_useraccount_id_permissio_ef1507c2_uniq UNIQUE (useraccount_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.warranty
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_deleted boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    warranty_start_date date NOT NULL,
    warranty_end_date date NOT NULL,
    serial_number character varying(100) COLLATE pg_catalog."default",
    status character varying(50) COLLATE pg_catalog."default",
    created_by bigint,
    order_detail_id bigint,
    updated_by bigint,
    CONSTRAINT warranty_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.warrantyclaim
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_deleted boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    claim_date date NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    resolution text COLLATE pg_catalog."default",
    status character varying(50) COLLATE pg_catalog."default",
    completed_date date,
    repair_cost numeric(10, 2),
    created_by bigint,
    technician_id bigint,
    updated_by bigint,
    warranty_id bigint,
    CONSTRAINT warrantyclaim_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.attributevalue
    ADD CONSTRAINT attributevalue_attribute_type_id_f48b7b5c_fk_attributetype_id FOREIGN KEY (attribute_type_id)
    REFERENCES public.attributetype (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS attributevalue_attribute_type_id_f48b7b5c
    ON public.attributevalue(attribute_type_id);


ALTER TABLE IF EXISTS public.audit_log
    ADD CONSTRAINT audit_log_user_id_a1b3392d_fk_useraccount_id FOREIGN KEY (user_id)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS audit_log_user_id_a1b3392d
    ON public.audit_log(user_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_permission_id_84c5c92e
    ON public.auth_group_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_group_id_b120cbf9
    ON public.auth_group_permissions(group_id);


ALTER TABLE IF EXISTS public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_permission_content_type_id_2f476e4b
    ON public.auth_permission(content_type_id);


ALTER TABLE IF EXISTS public.banner
    ADD CONSTRAINT banner_created_by_1ca16783_fk_useraccount_id FOREIGN KEY (created_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS banner_created_by_1ca16783
    ON public.banner(created_by);


ALTER TABLE IF EXISTS public.banner
    ADD CONSTRAINT banner_updated_by_6808cb09_fk_useraccount_id FOREIGN KEY (updated_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS banner_updated_by_6808cb09
    ON public.banner(updated_by);


ALTER TABLE IF EXISTS public.brand
    ADD CONSTRAINT brand_created_by_1899eadd_fk_useraccount_id FOREIGN KEY (created_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS brand_created_by_1899eadd
    ON public.brand(created_by);


ALTER TABLE IF EXISTS public.brand
    ADD CONSTRAINT brand_updated_by_c0e58032_fk_useraccount_id FOREIGN KEY (updated_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS brand_updated_by_c0e58032
    ON public.brand(updated_by);


ALTER TABLE IF EXISTS public.category
    ADD CONSTRAINT category_created_by_3f3d957e_fk_useraccount_id FOREIGN KEY (created_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS category_created_by_3f3d957e
    ON public.category(created_by);


ALTER TABLE IF EXISTS public.category
    ADD CONSTRAINT category_parent_id_6d39ea7f_fk_category_id FOREIGN KEY (parent_id)
    REFERENCES public.category (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS category_parent_id_6d39ea7f
    ON public.category(parent_id);


ALTER TABLE IF EXISTS public.category
    ADD CONSTRAINT category_updated_by_d6928832_fk_useraccount_id FOREIGN KEY (updated_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS category_updated_by_d6928832
    ON public.category(updated_by);


ALTER TABLE IF EXISTS public.contactinfo
    ADD CONSTRAINT contactinfo_created_by_f05b07ee_fk_useraccount_id FOREIGN KEY (created_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS contactinfo_created_by_f05b07ee
    ON public.contactinfo(created_by);


ALTER TABLE IF EXISTS public.contactinfo
    ADD CONSTRAINT contactinfo_updated_by_23cf9a02_fk_useraccount_id FOREIGN KEY (updated_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS contactinfo_updated_by_23cf9a02
    ON public.contactinfo(updated_by);


ALTER TABLE IF EXISTS public.coupon
    ADD CONSTRAINT coupon_created_by_32f4cfd9_fk_useraccount_id FOREIGN KEY (created_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS coupon_created_by_32f4cfd9
    ON public.coupon(created_by);


ALTER TABLE IF EXISTS public.coupon
    ADD CONSTRAINT coupon_updated_by_3393b755_fk_useraccount_id FOREIGN KEY (updated_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS coupon_updated_by_3393b755
    ON public.coupon(updated_by);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_content_type_id_c4bce8eb
    ON public.django_admin_log(content_type_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_useraccount_id FOREIGN KEY (user_id)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_user_id_c564eba6
    ON public.django_admin_log(user_id);


ALTER TABLE IF EXISTS public.employee
    ADD CONSTRAINT employee_store_id_3dd7fc81_fk_store_id FOREIGN KEY (store_id)
    REFERENCES public.store (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS employee_store_id_3dd7fc81
    ON public.employee(store_id);


ALTER TABLE IF EXISTS public.employee
    ADD CONSTRAINT employee_user_id_cc4f5a1c_fk_useraccount_id FOREIGN KEY (user_id)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS employee_user_id_cc4f5a1c
    ON public.employee(user_id);


ALTER TABLE IF EXISTS public.footercategory
    ADD CONSTRAINT footercategory_created_by_faff3d1f_fk_useraccount_id FOREIGN KEY (created_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS footercategory_created_by_faff3d1f
    ON public.footercategory(created_by);


ALTER TABLE IF EXISTS public.footercategory
    ADD CONSTRAINT footercategory_updated_by_bec34b61_fk_useraccount_id FOREIGN KEY (updated_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS footercategory_updated_by_bec34b61
    ON public.footercategory(updated_by);


ALTER TABLE IF EXISTS public.footerlink
    ADD CONSTRAINT footerlink_category_id_2ccc38a9_fk_footercategory_id FOREIGN KEY (category_id)
    REFERENCES public.footercategory (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS footerlink_category_id_2ccc38a9
    ON public.footerlink(category_id);


ALTER TABLE IF EXISTS public.footerlink
    ADD CONSTRAINT footerlink_created_by_1338a82e_fk_useraccount_id FOREIGN KEY (created_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS footerlink_created_by_1338a82e
    ON public.footerlink(created_by);


ALTER TABLE IF EXISTS public.footerlink
    ADD CONSTRAINT footerlink_updated_by_695a2b7a_fk_useraccount_id FOREIGN KEY (updated_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS footerlink_updated_by_695a2b7a
    ON public.footerlink(updated_by);


ALTER TABLE IF EXISTS public.inventory
    ADD CONSTRAINT inventory_product_variant_id_001672ba_fk_productvariant_id FOREIGN KEY (product_variant_id)
    REFERENCES public.productvariant (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS inventory_product_variant_id_001672ba
    ON public.inventory(product_variant_id);


ALTER TABLE IF EXISTS public.inventory
    ADD CONSTRAINT inventory_store_id_15a147d1_fk_store_id FOREIGN KEY (store_id)
    REFERENCES public.store (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS inventory_store_id_15a147d1
    ON public.inventory(store_id);


ALTER TABLE IF EXISTS public.inventorytransaction
    ADD CONSTRAINT inventorytransaction_created_by_21d49c97_fk_useraccount_id FOREIGN KEY (created_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS inventorytransaction_created_by_21d49c97
    ON public.inventorytransaction(created_by);


ALTER TABLE IF EXISTS public.inventorytransaction
    ADD CONSTRAINT inventorytransaction_inventory_id_65b23f8e_fk_inventory_id FOREIGN KEY (inventory_id)
    REFERENCES public.inventory (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS inventorytransaction_inventory_id_65b23f8e
    ON public.inventorytransaction(inventory_id);


ALTER TABLE IF EXISTS public.inventorytransaction
    ADD CONSTRAINT inventorytransaction_updated_by_2c85e43d_fk_useraccount_id FOREIGN KEY (updated_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS inventorytransaction_updated_by_2c85e43d
    ON public.inventorytransaction(updated_by);


ALTER TABLE IF EXISTS public.news
    ADD CONSTRAINT news_category_id_798ee23f_fk_newscategory_id FOREIGN KEY (category_id)
    REFERENCES public.newscategory (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS news_category_id_798ee23f
    ON public.news(category_id);


ALTER TABLE IF EXISTS public.news
    ADD CONSTRAINT news_created_by_b4d0a194_fk_useraccount_id FOREIGN KEY (created_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS news_created_by_b4d0a194
    ON public.news(created_by);


ALTER TABLE IF EXISTS public.news
    ADD CONSTRAINT news_updated_by_cc0676b7_fk_useraccount_id FOREIGN KEY (updated_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS news_updated_by_cc0676b7
    ON public.news(updated_by);


ALTER TABLE IF EXISTS public.newscategory
    ADD CONSTRAINT newscategory_created_by_a2ceaad4_fk_useraccount_id FOREIGN KEY (created_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS newscategory_created_by_a2ceaad4
    ON public.newscategory(created_by);


ALTER TABLE IF EXISTS public.newscategory
    ADD CONSTRAINT newscategory_updated_by_0154311f_fk_useraccount_id FOREIGN KEY (updated_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS newscategory_updated_by_0154311f
    ON public.newscategory(updated_by);


ALTER TABLE IF EXISTS public.orderdetail
    ADD CONSTRAINT orderdetail_order_id_e24e54cb_fk_orders_id FOREIGN KEY (order_id)
    REFERENCES public.orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS orderdetail_order_id_e24e54cb
    ON public.orderdetail(order_id);


ALTER TABLE IF EXISTS public.orderdetail
    ADD CONSTRAINT orderdetail_product_variant_id_700e4859_fk_productvariant_id FOREIGN KEY (product_variant_id)
    REFERENCES public.productvariant (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS orderdetail_product_variant_id_700e4859
    ON public.orderdetail(product_variant_id);


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_created_by_79c17996_fk_useraccount_id FOREIGN KEY (created_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS orders_created_by_79c17996
    ON public.orders(created_by);


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_customer_id_b7016332_fk_orders_customer_id FOREIGN KEY (customer_id)
    REFERENCES public.orders_customer (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS orders_customer_id_b7016332
    ON public.orders(customer_id);


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_employee_id_098e8632_fk_employee_id FOREIGN KEY (employee_id)
    REFERENCES public.employee (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS orders_employee_id_098e8632
    ON public.orders(employee_id);


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_store_id_04cf6eb1_fk_store_id FOREIGN KEY (store_id)
    REFERENCES public.store (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS orders_store_id_04cf6eb1
    ON public.orders(store_id);


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_updated_by_5a3cf0de_fk_useraccount_id FOREIGN KEY (updated_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS orders_updated_by_5a3cf0de
    ON public.orders(updated_by);


ALTER TABLE IF EXISTS public.orders_customer
    ADD CONSTRAINT orders_customer_created_by_id_7bfea52c_fk_useraccount_id FOREIGN KEY (created_by_id)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS orders_customer_created_by_id_7bfea52c
    ON public.orders_customer(created_by_id);


ALTER TABLE IF EXISTS public.orders_customer
    ADD CONSTRAINT orders_customer_updated_by_id_40ba0b58_fk_useraccount_id FOREIGN KEY (updated_by_id)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS orders_customer_updated_by_id_40ba0b58
    ON public.orders_customer(updated_by_id);


ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT product_brand_id_9bf06fde_fk_brand_id FOREIGN KEY (brand_id)
    REFERENCES public.brand (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS product_brand_id_9bf06fde
    ON public.product(brand_id);


ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT product_category_id_640030a0_fk_category_id FOREIGN KEY (category_id)
    REFERENCES public.category (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS product_category_id_640030a0
    ON public.product(category_id);


ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT product_created_by_8003fc71_fk_useraccount_id FOREIGN KEY (created_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS product_created_by_8003fc71
    ON public.product(created_by);


ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT product_updated_by_1b5bad6b_fk_useraccount_id FOREIGN KEY (updated_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS product_updated_by_1b5bad6b
    ON public.product(updated_by);


ALTER TABLE IF EXISTS public.productimage
    ADD CONSTRAINT productimage_created_by_7735ba11_fk_useraccount_id FOREIGN KEY (created_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS productimage_created_by_7735ba11
    ON public.productimage(created_by);


ALTER TABLE IF EXISTS public.productimage
    ADD CONSTRAINT productimage_product_id_0c64cc4d_fk_product_id FOREIGN KEY (product_id)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS productimage_product_id_0c64cc4d
    ON public.productimage(product_id);


ALTER TABLE IF EXISTS public.productimage
    ADD CONSTRAINT productimage_product_variant_id_59e037ff_fk_productvariant_id FOREIGN KEY (product_variant_id)
    REFERENCES public.productvariant (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS productimage_product_variant_id_59e037ff
    ON public.productimage(product_variant_id);


ALTER TABLE IF EXISTS public.productimage
    ADD CONSTRAINT productimage_updated_by_525e78c5_fk_useraccount_id FOREIGN KEY (updated_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS productimage_updated_by_525e78c5
    ON public.productimage(updated_by);


ALTER TABLE IF EXISTS public.productvariant
    ADD CONSTRAINT productvariant_created_by_4aa04988_fk_useraccount_id FOREIGN KEY (created_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS productvariant_created_by_4aa04988
    ON public.productvariant(created_by);


ALTER TABLE IF EXISTS public.productvariant
    ADD CONSTRAINT productvariant_product_id_1ad21f13_fk_product_id FOREIGN KEY (product_id)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS productvariant_product_id_1ad21f13
    ON public.productvariant(product_id);


ALTER TABLE IF EXISTS public.productvariant
    ADD CONSTRAINT productvariant_updated_by_bfae0a26_fk_useraccount_id FOREIGN KEY (updated_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS productvariant_updated_by_bfae0a26
    ON public.productvariant(updated_by);


ALTER TABLE IF EXISTS public.productvariantattribute
    ADD CONSTRAINT productvariantattrib_attribute_value_id_fe05fd96_fk_attribute FOREIGN KEY (attribute_value_id)
    REFERENCES public.attributevalue (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS productvariantattribute_attribute_value_id_fe05fd96
    ON public.productvariantattribute(attribute_value_id);


ALTER TABLE IF EXISTS public.productvariantattribute
    ADD CONSTRAINT productvariantattrib_product_variant_id_53df6599_fk_productva FOREIGN KEY (product_variant_id)
    REFERENCES public.productvariant (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS productvariantattribute_product_variant_id_53df6599
    ON public.productvariantattribute(product_variant_id);


ALTER TABLE IF EXISTS public.returnorder
    ADD CONSTRAINT returnorder_created_by_2064e065_fk_useraccount_id FOREIGN KEY (created_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS returnorder_created_by_2064e065
    ON public.returnorder(created_by);


ALTER TABLE IF EXISTS public.returnorder
    ADD CONSTRAINT returnorder_customer_id_9e6527a1_fk_orders_customer_id FOREIGN KEY (customer_id)
    REFERENCES public.orders_customer (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS returnorder_customer_id_9e6527a1
    ON public.returnorder(customer_id);


ALTER TABLE IF EXISTS public.returnorder
    ADD CONSTRAINT returnorder_order_id_bdeae2df_fk_orders_id FOREIGN KEY (order_id)
    REFERENCES public.orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS returnorder_order_id_bdeae2df
    ON public.returnorder(order_id);


ALTER TABLE IF EXISTS public.returnorder
    ADD CONSTRAINT returnorder_updated_by_d30b3462_fk_useraccount_id FOREIGN KEY (updated_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS returnorder_updated_by_d30b3462
    ON public.returnorder(updated_by);


ALTER TABLE IF EXISTS public.returnorderdetail
    ADD CONSTRAINT returnorderdetail_order_detail_id_a635282a_fk_orderdetail_id FOREIGN KEY (order_detail_id)
    REFERENCES public.orderdetail (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS returnorderdetail_order_detail_id_a635282a
    ON public.returnorderdetail(order_detail_id);


ALTER TABLE IF EXISTS public.returnorderdetail
    ADD CONSTRAINT returnorderdetail_product_variant_id_9450873d_fk_productva FOREIGN KEY (product_variant_id)
    REFERENCES public.productvariant (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS returnorderdetail_product_variant_id_9450873d
    ON public.returnorderdetail(product_variant_id);


ALTER TABLE IF EXISTS public.returnorderdetail
    ADD CONSTRAINT returnorderdetail_return_order_id_b2f41077_fk_returnorder_id FOREIGN KEY (return_order_id)
    REFERENCES public.returnorder (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS returnorderdetail_return_order_id_b2f41077
    ON public.returnorderdetail(return_order_id);


ALTER TABLE IF EXISTS public.stocktake
    ADD CONSTRAINT stocktake_created_by_1ca1e288_fk_useraccount_id FOREIGN KEY (created_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS stocktake_created_by_1ca1e288
    ON public.stocktake(created_by);


ALTER TABLE IF EXISTS public.stocktake
    ADD CONSTRAINT stocktake_store_id_e44d1240_fk_store_id FOREIGN KEY (store_id)
    REFERENCES public.store (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS stocktake_store_id_e44d1240
    ON public.stocktake(store_id);


ALTER TABLE IF EXISTS public.stocktake
    ADD CONSTRAINT stocktake_updated_by_51922bde_fk_useraccount_id FOREIGN KEY (updated_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS stocktake_updated_by_51922bde
    ON public.stocktake(updated_by);


ALTER TABLE IF EXISTS public.stocktakedetail
    ADD CONSTRAINT stocktakedetail_product_variant_id_e104c0d3_fk_productva FOREIGN KEY (product_variant_id)
    REFERENCES public.productvariant (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS stocktakedetail_product_variant_id_e104c0d3
    ON public.stocktakedetail(product_variant_id);


ALTER TABLE IF EXISTS public.stocktakedetail
    ADD CONSTRAINT stocktakedetail_stock_take_id_5a224eda_fk_stocktake_id FOREIGN KEY (stock_take_id)
    REFERENCES public.stocktake (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS stocktakedetail_stock_take_id_5a224eda
    ON public.stocktakedetail(stock_take_id);


ALTER TABLE IF EXISTS public.stocktransfer
    ADD CONSTRAINT stocktransfer_created_by_ff40f447_fk_useraccount_id FOREIGN KEY (created_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS stocktransfer_created_by_ff40f447
    ON public.stocktransfer(created_by);


ALTER TABLE IF EXISTS public.stocktransfer
    ADD CONSTRAINT stocktransfer_destination_store_id_b2d105b4_fk_store_id FOREIGN KEY (destination_store_id)
    REFERENCES public.store (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS stocktransfer_destination_store_id_b2d105b4
    ON public.stocktransfer(destination_store_id);


ALTER TABLE IF EXISTS public.stocktransfer
    ADD CONSTRAINT stocktransfer_source_store_id_f68c540b_fk_store_id FOREIGN KEY (source_store_id)
    REFERENCES public.store (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS stocktransfer_source_store_id_f68c540b
    ON public.stocktransfer(source_store_id);


ALTER TABLE IF EXISTS public.stocktransfer
    ADD CONSTRAINT stocktransfer_updated_by_4bf6515e_fk_useraccount_id FOREIGN KEY (updated_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS stocktransfer_updated_by_4bf6515e
    ON public.stocktransfer(updated_by);


ALTER TABLE IF EXISTS public.stocktransferdetail
    ADD CONSTRAINT stocktransferdetail_product_variant_id_5fd5532a_fk_productva FOREIGN KEY (product_variant_id)
    REFERENCES public.productvariant (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS stocktransferdetail_product_variant_id_5fd5532a
    ON public.stocktransferdetail(product_variant_id);


ALTER TABLE IF EXISTS public.stocktransferdetail
    ADD CONSTRAINT stocktransferdetail_stock_transfer_id_bb7fd2e0_fk_stocktran FOREIGN KEY (stock_transfer_id)
    REFERENCES public.stocktransfer (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS stocktransferdetail_stock_transfer_id_bb7fd2e0
    ON public.stocktransferdetail(stock_transfer_id);


ALTER TABLE IF EXISTS public.store
    ADD CONSTRAINT store_created_by_09409afb_fk_useraccount_id FOREIGN KEY (created_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS store_created_by_09409afb
    ON public.store(created_by);


ALTER TABLE IF EXISTS public.store
    ADD CONSTRAINT store_manager_id_d7cce0e7_fk_employee_id FOREIGN KEY (manager_id)
    REFERENCES public.employee (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS store_manager_id_d7cce0e7
    ON public.store(manager_id);


ALTER TABLE IF EXISTS public.store
    ADD CONSTRAINT store_updated_by_2ce0990a_fk_useraccount_id FOREIGN KEY (updated_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS store_updated_by_2ce0990a
    ON public.store(updated_by);


ALTER TABLE IF EXISTS public.supplier
    ADD CONSTRAINT supplier_created_by_adecd657_fk_useraccount_id FOREIGN KEY (created_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS supplier_created_by_adecd657
    ON public.supplier(created_by);


ALTER TABLE IF EXISTS public.supplier
    ADD CONSTRAINT supplier_updated_by_e8c145fb_fk_useraccount_id FOREIGN KEY (updated_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS supplier_updated_by_e8c145fb
    ON public.supplier(updated_by);


ALTER TABLE IF EXISTS public.useraccount_groups
    ADD CONSTRAINT useraccount_groups_group_id_1f96b709_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS useraccount_groups_group_id_1f96b709
    ON public.useraccount_groups(group_id);


ALTER TABLE IF EXISTS public.useraccount_groups
    ADD CONSTRAINT useraccount_groups_useraccount_id_6215c48c_fk_useraccount_id FOREIGN KEY (useraccount_id)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS useraccount_groups_useraccount_id_6215c48c
    ON public.useraccount_groups(useraccount_id);


ALTER TABLE IF EXISTS public.useraccount_user_permissions
    ADD CONSTRAINT useraccount_user_per_permission_id_d16b1cfe_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS useraccount_user_permissions_permission_id_d16b1cfe
    ON public.useraccount_user_permissions(permission_id);


ALTER TABLE IF EXISTS public.useraccount_user_permissions
    ADD CONSTRAINT useraccount_user_per_useraccount_id_a107e2ef_fk_useraccou FOREIGN KEY (useraccount_id)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS useraccount_user_permissions_useraccount_id_a107e2ef
    ON public.useraccount_user_permissions(useraccount_id);


ALTER TABLE IF EXISTS public.warranty
    ADD CONSTRAINT warranty_created_by_80063082_fk_useraccount_id FOREIGN KEY (created_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS warranty_created_by_80063082
    ON public.warranty(created_by);


ALTER TABLE IF EXISTS public.warranty
    ADD CONSTRAINT warranty_order_detail_id_93cebc83_fk_orderdetail_id FOREIGN KEY (order_detail_id)
    REFERENCES public.orderdetail (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS warranty_order_detail_id_93cebc83
    ON public.warranty(order_detail_id);


ALTER TABLE IF EXISTS public.warranty
    ADD CONSTRAINT warranty_updated_by_705994aa_fk_useraccount_id FOREIGN KEY (updated_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS warranty_updated_by_705994aa
    ON public.warranty(updated_by);


ALTER TABLE IF EXISTS public.warrantyclaim
    ADD CONSTRAINT warrantyclaim_created_by_bf1e40d0_fk_useraccount_id FOREIGN KEY (created_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS warrantyclaim_created_by_bf1e40d0
    ON public.warrantyclaim(created_by);


ALTER TABLE IF EXISTS public.warrantyclaim
    ADD CONSTRAINT warrantyclaim_technician_id_931380e3_fk_employee_id FOREIGN KEY (technician_id)
    REFERENCES public.employee (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS warrantyclaim_technician_id_931380e3
    ON public.warrantyclaim(technician_id);


ALTER TABLE IF EXISTS public.warrantyclaim
    ADD CONSTRAINT warrantyclaim_updated_by_ade6d4fd_fk_useraccount_id FOREIGN KEY (updated_by)
    REFERENCES public.useraccount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS warrantyclaim_updated_by_ade6d4fd
    ON public.warrantyclaim(updated_by);


ALTER TABLE IF EXISTS public.warrantyclaim
    ADD CONSTRAINT warrantyclaim_warranty_id_d17f9adb_fk_warranty_id FOREIGN KEY (warranty_id)
    REFERENCES public.warranty (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS warrantyclaim_warranty_id_d17f9adb
    ON public.warrantyclaim(warranty_id);

END;