# Generated by Django 5.0.2 on 2025-07-15 20:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("quantity", models.IntegerField(default=0)),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "db_table": "inventory",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("transaction_type", models.CharField(max_length=20)),
                ("quantity", models.IntegerField()),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=25, null=True
                    ),
                ),
                ("reference_id", models.IntegerField(blank=True, null=True)),
                (
                    "reference_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("transaction_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "inventorytransaction",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="StockTake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "stocktake",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="StockTakeDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expected_quantity", models.IntegerField(blank=True, null=True)),
                ("actual_quantity", models.IntegerField(blank=True, null=True)),
                ("discrepancy", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "stocktakedetail",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="StockTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("transfer_date", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("note", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "stocktransfer",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="StockTransferDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("quantity", models.IntegerField()),
                ("received_quantity", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "stocktransferdetail",
                "managed": True,
            },
        ),
    ]
