# Generated by Django 5.0.2 on 2025-05-12 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_initial'),
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventorytransaction_updated_by_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stores.store'),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stocktake_updated_by_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktakedetail',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='stocktakedetail',
            name='stock_take',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.stocktake'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='destination_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stocktransfer_destination_store_set', to='stores.store'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='source_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stores.store'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stocktransfer_updated_by_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransferdetail',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='stocktransferdetail',
            name='stock_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.stocktransfer'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product_variant', 'store')},
        ),
    ]
