# Generated by Django 5.0.2 on 2025-06-10 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_partial_unique_index'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
    ]
