# Generated by Django 5.0.2 on 2025-06-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_inventory_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
    ]
