# Generated by Django 5.0.2 on 2025-07-15 20:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("code", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed", "Fixed Amount"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, max_digits=25),
                ),
                (
                    "minimum_order_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=25, null=True
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("usage_limit", models.IntegerField(default=1)),
                ("usage_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "coupon",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField(blank=True, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "customer",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("quantity", models.IntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=25)),
                (
                    "discount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=25, null=True
                    ),
                ),
                ("final_price", models.DecimalField(decimal_places=2, max_digits=25)),
            ],
            options={
                "db_table": "orderdetail",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("order_date", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "payment_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("shipping_address", models.TextField(blank=True, null=True)),
                (
                    "shipping_method",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=25),
                ),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=25),
                ),
                (
                    "shipping_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=25),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=25),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=25),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("is_online_order", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "orders",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ReturnOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("return_date", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Chờ xử lý"),
                            ("APPROVED", "Đã duyệt"),
                            ("REJECTED", "Từ chối"),
                            ("COMPLETED", "Hoàn thành"),
                            ("CANCELLED", "Đã hủy"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=25, null=True
                    ),
                ),
                (
                    "refund_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "refund_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Chờ hoàn tiền"),
                            ("PROCESSING", "Đang xử lý"),
                            ("COMPLETED", "Đã hoàn tiền"),
                            ("FAILED", "Hoàn tiền thất bại"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                (
                    "return_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "returnorder",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ReturnOrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("quantity", models.IntegerField()),
                ("reason", models.TextField(blank=True, null=True)),
                ("condition", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "returnorderdetail",
                "managed": True,
            },
        ),
    ]
