# Generated by Django 5.0.2 on 2025-07-02 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_alter_coupon_discount_value_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="returnorder",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="return_orders_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="returnorder",
            name="approved_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="returnorder",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="returnorder",
            name="return_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="returnorder",
            name="refund_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Chờ hoàn tiền"),
                    ("PROCESSING", "Đang xử lý"),
                    ("COMPLETED", "Đã hoàn tiền"),
                    ("FAILED", "Hoàn tiền thất bại"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="returnorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Chờ xử lý"),
                    ("APPROVED", "Đã duyệt"),
                    ("REJECTED", "Từ chối"),
                    ("COMPLETED", "Hoàn thành"),
                    ("CANCELLED", "Đã hủy"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="returnorder",
            index=models.Index(
                fields=["return_number"], name="returnorder_return__915269_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="returnorder",
            index=models.Index(fields=["status"], name="returnorder_status_d594aa_idx"),
        ),
        migrations.AddIndex(
            model_name="returnorder",
            index=models.Index(
                fields=["return_date"], name="returnorder_return__13562a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="returnorder",
            index=models.Index(fields=["order"], name="returnorder_order_i_ec1416_idx"),
        ),
        migrations.AddIndex(
            model_name="returnorder",
            index=models.Index(
                fields=["customer"], name="returnorder_custome_53065c_idx"
            ),
        ),
    ]
