# Generated by Django 5.0.2 on 2025-07-04 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_returnorder_approved_by_returnorder_approved_date_and_more"),
        ("stores", "0009_employee_is_manager"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="returnorder",
            name="return_store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="return_orders",
                to="stores.store",
            ),
        ),
        migrations.AddIndex(
            model_name="returnorder",
            index=models.Index(
                fields=["return_store"], name="returnorder_return__619ef2_idx"
            ),
        ),
    ]
