# Generated by Django 5.0.2 on 2025-07-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_returnorder_return_store_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="usage_count",
            field=models.IntegerField(default=0),
        ),
    ]
