# Generated by Django 5.0.2 on 2025-07-11 19:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_fix_coupon_usage_count_null"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="code",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="coupon",
            unique_together={("code", "is_deleted")},
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(fields=["code"], name="coupon_code_c020c6_idx"),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(fields=["is_active"], name="coupon_is_acti_164a17_idx"),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(fields=["start_date"], name="coupon_start_d_e42759_idx"),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(fields=["expires_at"], name="coupon_expires_faba28_idx"),
        ),
    ]
