# Generated by Django 5.0.2 on 2025-06-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_employee_created_by_employee_updated_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'managed': True, 'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
