# Generated by Django 5.0.2 on 2025-06-09 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_alter_store_options_alter_store_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='opening_date',
        ),
    ]
