# Generated by Django 5.0.2 on 2025-07-15 20:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                        ],
                        max_length=10,
                    ),
                ),
                ("model_name", models.CharField(max_length=255)),
                ("object_id", models.CharField(max_length=255)),
                ("old_values", models.JSONField(blank=True, null=True)),
                ("new_values", models.JSONField(blank=True, null=True)),
                ("user_id", models.IntegerField(null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("action_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "audit_log",
                "ordering": ["-action_date"],
            },
        ),
    ]
