# Generated by Django 5.0.2 on 2025-05-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_auditlog_created_at_alter_auditlog_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
