# Generated by Django 5.0.2 on 2025-07-15 20:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Warranty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("warranty_start_date", models.DateField()),
                ("warranty_end_date", models.DateField()),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Đang hiệu lực"),
                            ("EXPIRED", "Hết hạn"),
                            ("CLAIMED", "Đang bảo hành"),
                            ("CANCELLED", "Đã hủy"),
                        ],
                        default="ACTIVE",
                        max_length=50,
                    ),
                ),
                (
                    "warranty_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order_detail",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="orders.orderdetail",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="warranty_updated_by_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "warranty",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="WarrantyClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("claim_date", models.DateField()),
                ("description", models.TextField()),
                ("resolution", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Chờ xử lý"),
                            ("IN_PROGRESS", "Đang xử lý"),
                            ("COMPLETED", "Hoàn thành"),
                            ("REJECTED", "Từ chối"),
                            ("CANCELLED", "Đã hủy"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("completed_date", models.DateField(blank=True, null=True)),
                (
                    "repair_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=25, null=True
                    ),
                ),
                (
                    "claim_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("estimated_completion_date", models.DateField(blank=True, null=True)),
                (
                    "customer_contact",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="stores.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="warrantyclaim_updated_by_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warranty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="warranty.warranty",
                    ),
                ),
            ],
            options={
                "db_table": "warrantyclaim",
                "managed": True,
            },
        ),
        migrations.AddIndex(
            model_name="warranty",
            index=models.Index(
                fields=["warranty_number"], name="warranty_warrant_757aeb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warranty",
            index=models.Index(fields=["status"], name="warranty_status_c34275_idx"),
        ),
        migrations.AddIndex(
            model_name="warranty",
            index=models.Index(
                fields=["warranty_start_date"], name="warranty_warrant_b68a7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warranty",
            index=models.Index(
                fields=["warranty_end_date"], name="warranty_warrant_137ddc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warrantyclaim",
            index=models.Index(
                fields=["claim_number"], name="warrantycla_claim_n_5831f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warrantyclaim",
            index=models.Index(fields=["status"], name="warrantycla_status_afc0ba_idx"),
        ),
        migrations.AddIndex(
            model_name="warrantyclaim",
            index=models.Index(
                fields=["claim_date"], name="warrantycla_claim_d_469822_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warrantyclaim",
            index=models.Index(
                fields=["warranty"], name="warrantycla_warrant_f2c45f_idx"
            ),
        ),
    ]
