# Generated by Django 5.0.2 on 2025-07-02 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_returnorder_approved_by_returnorder_approved_date_and_more"),
        ("stores", "0009_employee_is_manager"),
        ("warranty", "0003_alter_warrantyclaim_repair_cost"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="warranty",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="warranty",
            name="warranty_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="warrantyclaim",
            name="claim_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="warrantyclaim",
            name="customer_contact",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="warrantyclaim",
            name="estimated_completion_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="warranty",
            name="status",
            field=models.CharField(
                blank=True, default="ACTIVE", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="warrantyclaim",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Chờ xử lý"),
                    ("IN_PROGRESS", "Đang xử lý"),
                    ("COMPLETED", "Hoàn thành"),
                    ("REJECTED", "Từ chối"),
                    ("CANCELLED", "Đã hủy"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="warranty",
            index=models.Index(
                fields=["warranty_number"], name="warranty_warrant_757aeb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warranty",
            index=models.Index(fields=["status"], name="warranty_status_c34275_idx"),
        ),
        migrations.AddIndex(
            model_name="warranty",
            index=models.Index(
                fields=["warranty_start_date"], name="warranty_warrant_b68a7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warranty",
            index=models.Index(
                fields=["warranty_end_date"], name="warranty_warrant_137ddc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warrantyclaim",
            index=models.Index(
                fields=["claim_number"], name="warrantycla_claim_n_5831f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warrantyclaim",
            index=models.Index(fields=["status"], name="warrantycla_status_afc0ba_idx"),
        ),
        migrations.AddIndex(
            model_name="warrantyclaim",
            index=models.Index(
                fields=["claim_date"], name="warrantycla_claim_d_469822_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warrantyclaim",
            index=models.Index(
                fields=["warranty"], name="warrantycla_warrant_f2c45f_idx"
            ),
        ),
    ]
