# Generated by Django 5.0.2 on 2025-07-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warranty", "0004_warranty_notes_warranty_warranty_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warranty",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Đang hiệu lực"),
                    ("EXPIRED", "Hết hạn"),
                    ("CLAIMED", "Đang bảo hành"),
                    ("CANCELLED", "Đã hủy"),
                ],
                default="ACTIVE",
                max_length=50,
            ),
        ),
    ]
