# Generated by Django 5.1.7 on 2025-04-01 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_attribute_attributevalue_coupon_loginhistory_and_more'),
    ]

    operations = [
    ]
