# Generated by Django 5.0.2 on 2025-07-01 09:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_alter_product_base_price_and_more"),
        ("reports", "0001_initial"),
        ("stores", "0009_employee_is_manager"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("date", models.DateField()),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("opening_stock", models.IntegerField(default=0)),
                ("closing_stock", models.IntegerField(default=0)),
                (
                    "average_stock",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("stock_in", models.IntegerField(default=0)),
                (
                    "stock_in_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=25),
                ),
                ("stock_out", models.IntegerField(default=0)),
                (
                    "stock_out_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=25),
                ),
                ("stock_transfer_in", models.IntegerField(default=0)),
                ("stock_transfer_out", models.IntegerField(default=0)),
                (
                    "stock_turnover_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("days_of_inventory", models.IntegerField(default=0)),
                (
                    "stock_accuracy",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "stock_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=25),
                ),
                (
                    "average_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=25),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product_variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="products.productvariant",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="stores.store",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="inventory_analysis_updated_by_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "inventory_analysis",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["store", "product_variant", "date"],
                        name="inventory_a_store_i_2c4a81_idx",
                    ),
                    models.Index(
                        fields=["period_type", "date"],
                        name="inventory_a_period__a3e0cc_idx",
                    ),
                ],
                "unique_together": {
                    ("store", "product_variant", "date", "period_type")
                },
            },
        ),
        migrations.CreateModel(
            name="SalesAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("date", models.DateField()),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity_sold", models.IntegerField(default=0)),
                ("quantity_returned", models.IntegerField(default=0)),
                ("net_quantity", models.IntegerField(default=0)),
                (
                    "gross_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=25),
                ),
                (
                    "net_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=25),
                ),
                (
                    "cost_of_goods_sold",
                    models.DecimalField(decimal_places=2, default=0, max_digits=25),
                ),
                (
                    "gross_profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=25),
                ),
                (
                    "gross_profit_margin",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "total_discounts",
                    models.DecimalField(decimal_places=2, default=0, max_digits=25),
                ),
                (
                    "coupon_discounts",
                    models.DecimalField(decimal_places=2, default=0, max_digits=25),
                ),
                ("total_orders", models.IntegerField(default=0)),
                (
                    "average_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=25),
                ),
                ("stock_level", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product_variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="products.productvariant",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="stores.store",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="sales_analysis_updated_by_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sales_analysis",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["store", "product_variant", "date"],
                        name="sales_analy_store_i_ac5840_idx",
                    ),
                    models.Index(
                        fields=["period_type", "date"],
                        name="sales_analy_period__691cc3_idx",
                    ),
                ],
                "unique_together": {
                    ("store", "product_variant", "date", "period_type")
                },
            },
        ),
    ]
