# Generated by Django 5.0.2 on 2025-07-01 09:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0002_inventoryanalysis_salesanalysis"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="salesanalysis",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="salesanalysis",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="salesanalysis",
            name="product_variant",
        ),
        migrations.RemoveField(
            model_name="salesanalysis",
            name="store",
        ),
        migrations.RemoveField(
            model_name="salesanalysis",
            name="updated_by",
        ),
        migrations.DeleteModel(
            name="InventoryAnalysis",
        ),
        migrations.DeleteModel(
            name="SalesAnalysis",
        ),
    ]
