# Generated by Django 5.0.2 on 2025-07-15 05:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0004_report_delete_dailyrevenue_delete_topproduct"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Report",
        ),
    ]
