# Generated by Django 5.0.2 on 2025-07-15 20:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GoodsReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "receipt_number",
                    models.CharField(max_length=50, verbose_name="Mã phiếu nhập"),
                ),
                ("receipt_date", models.DateTimeField(verbose_name="Ngày nhập kho")),
                (
                    "expected_receipt_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ngày nhập kho dự kiến"
                    ),
                ),
                (
                    "delivery_note",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Số phiếu giao hàng"
                    ),
                ),
                (
                    "vehicle_number",
                    models.CharField(blank=True, max_length=20, verbose_name="Số xe"),
                ),
                (
                    "driver_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tên tài xế"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Nháp"),
                            ("pending", "Chờ xác nhận"),
                            ("confirmed", "Đã xác nhận"),
                            ("completed", "Hoàn thành"),
                            ("cancelled", "Đã hủy"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Tổng tiền hàng",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Thuế"
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Giảm giá",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Tổng tiền",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Ghi chú")),
                (
                    "quality_check_notes",
                    models.TextField(
                        blank=True, verbose_name="Ghi chú kiểm tra chất lượng"
                    ),
                ),
                (
                    "is_quality_checked",
                    models.BooleanField(
                        default=False, verbose_name="Đã kiểm tra chất lượng"
                    ),
                ),
            ],
            options={
                "verbose_name": "Phiếu nhập kho",
                "verbose_name_plural": "Phiếu nhập kho",
                "db_table": "goods_receipts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GoodsReceiptDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ordered_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Số lượng đã đặt"
                    ),
                ),
                (
                    "received_quantity",
                    models.PositiveIntegerField(verbose_name="Số lượng nhập"),
                ),
                (
                    "accepted_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Số lượng chấp nhận"
                    ),
                ),
                (
                    "rejected_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Số lượng từ chối"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Đơn giá"
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Phần trăm giảm giá",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Số tiền giảm giá",
                    ),
                ),
                (
                    "tax_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Phần trăm thuế",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Số tiền thuế",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Thành tiền"
                    ),
                ),
                (
                    "quality_status",
                    models.CharField(
                        choices=[
                            ("pending", "Chờ kiểm tra"),
                            ("accepted", "Chấp nhận"),
                            ("rejected", "Từ chối"),
                            ("partial", "Chấp nhận một phần"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Trạng thái chất lượng",
                    ),
                ),
                (
                    "quality_notes",
                    models.TextField(blank=True, verbose_name="Ghi chú chất lượng"),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày hết hạn"
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=50, verbose_name="Số lô"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Ghi chú")),
            ],
            options={
                "verbose_name": "Chi tiết phiếu nhập kho",
                "verbose_name_plural": "Chi tiết phiếu nhập kho",
                "db_table": "goods_receipt_details",
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "po_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Mã đơn đặt hàng"
                    ),
                ),
                ("order_date", models.DateTimeField(verbose_name="Ngày đặt hàng")),
                (
                    "expected_delivery_date",
                    models.DateTimeField(verbose_name="Ngày giao hàng dự kiến"),
                ),
                (
                    "actual_delivery_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ngày giao hàng thực tế"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Nháp"),
                            ("pending", "Chờ xác nhận"),
                            ("confirmed", "Đã xác nhận"),
                            ("ordered", "Đã đặt hàng"),
                            ("receiving", "Đang nhận hàng"),
                            ("completed", "Hoàn thành"),
                            ("cancelled", "Đã hủy"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Điều khoản thanh toán"
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Chưa thanh toán"),
                            ("partial", "Thanh toán một phần"),
                            ("paid", "Đã thanh toán"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Trạng thái thanh toán",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Tổng tiền hàng",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Thuế"
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Giảm giá",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Tổng tiền",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Số tiền đã thanh toán",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Ghi chú")),
                (
                    "shipping_address",
                    models.TextField(blank=True, verbose_name="Địa chỉ giao hàng"),
                ),
                (
                    "shipping_method",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Phương thức vận chuyển",
                    ),
                ),
            ],
            options={
                "verbose_name": "Đơn đặt hàng mua",
                "verbose_name_plural": "Đơn đặt hàng mua",
                "db_table": "purchase_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("quantity", models.PositiveIntegerField(verbose_name="Số lượng đặt")),
                (
                    "received_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Số lượng đã nhận"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Đơn giá"
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Phần trăm giảm giá",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Số tiền giảm giá",
                    ),
                ),
                (
                    "tax_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Phần trăm thuế",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Số tiền thuế",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Thành tiền"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Ghi chú")),
                (
                    "expected_delivery_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ngày giao hàng dự kiến"
                    ),
                ),
            ],
            options={
                "verbose_name": "Chi tiết đơn đặt hàng mua",
                "verbose_name_plural": "Chi tiết đơn đặt hàng mua",
                "db_table": "purchase_order_details",
            },
        ),
    ]
