# Generated by Django 5.0.2 on 2025-07-15 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0002_initial"),
        ("purchases", "0001_initial"),
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceipt",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="goods_receipts_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người tạo",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="stores.employee",
                verbose_name="Nhân viên tạo",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="store",
            field=models.ForeignKey(
                help_text="Tự động lấy từ đơn đặt hàng nếu có",
                on_delete=django.db.models.deletion.CASCADE,
                to="stores.store",
                verbose_name="Cửa hàng",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="supplier",
            field=models.ForeignKey(
                help_text="Tự động lấy từ đơn đặt hàng nếu có",
                on_delete=django.db.models.deletion.CASCADE,
                to="stores.supplier",
                verbose_name="Nhà cung cấp",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="goods_receipts_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người cập nhật",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptdetail",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptdetail",
            name="goods_receipt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="purchases.goodsreceipt",
                verbose_name="Phiếu nhập kho",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptdetail",
            name="product_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productvariant",
                verbose_name="Sản phẩm",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptdetail",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_orders_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người tạo",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="stores.employee",
                verbose_name="Nhân viên tạo",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="stores.store",
                verbose_name="Cửa hàng",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="stores.supplier",
                verbose_name="Nhà cung cấp",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_orders_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người cập nhật",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goods_receipts",
                to="purchases.purchaseorder",
                verbose_name="Đơn đặt hàng",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderdetail",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderdetail",
            name="product_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productvariant",
                verbose_name="Sản phẩm",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderdetail",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="purchases.purchaseorder",
                verbose_name="Đơn đặt hàng",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderdetail",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptdetail",
            name="purchase_order_detail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="purchases.purchaseorderdetail",
                verbose_name="Chi tiết đơn đặt hàng",
            ),
        ),
        migrations.AddConstraint(
            model_name="goodsreceipt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("purchase_order",),
                name="unique_purchase_order_not_deleted",
            ),
        ),
        migrations.AddConstraint(
            model_name="goodsreceipt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("receipt_number",),
                name="unique_receipt_number_not_deleted",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="purchaseorderdetail",
            unique_together={("purchase_order", "product_variant")},
        ),
        migrations.AddConstraint(
            model_name="goodsreceiptdetail",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("goods_receipt", "product_variant"),
                name="unique_goods_receipt_product_not_deleted",
            ),
        ),
    ]
