# Generated by Django 5.0.2 on 2025-06-21 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchases", "0001_initial"),
        ("stores", "0009_employee_is_manager"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goodsreceipt",
            name="paid_amount",
        ),
        migrations.RemoveField(
            model_name="goodsreceipt",
            name="payment_status",
        ),
        migrations.AlterField(
            model_name="goodsreceipt",
            name="store",
            field=models.ForeignKey(
                help_text="Tự động lấy từ đơn đặt hàng nếu có",
                on_delete=django.db.models.deletion.CASCADE,
                to="stores.store",
                verbose_name="Cửa hàng",
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceipt",
            name="supplier",
            field=models.ForeignKey(
                help_text="Tự động lấy từ đơn đặt hàng nếu có",
                on_delete=django.db.models.deletion.CASCADE,
                to="stores.supplier",
                verbose_name="Nhà cung cấp",
            ),
        ),
    ]
