# Generated by Django 5.0.2 on 2025-06-21 07:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("purchases", "0002_remove_goodsreceipt_paid_amount_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="goodsreceipt",
            unique_together={("purchase_order", "is_deleted")},
        ),
    ]
