# Generated by Django 5.0.2 on 2025-06-21 08:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchases", "0003_alter_goodsreceipt_unique_together"),
        ("stores", "0009_employee_is_manager"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsreceipt",
            name="receipt_number",
            field=models.CharField(max_length=50, verbose_name="Mã phiếu nhập"),
        ),
        migrations.AddConstraint(
            model_name="goodsreceipt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("receipt_number",),
                name="unique_receipt_number_not_deleted",
            ),
        ),
    ]
