# Generated by Django 5.0.2 on 2025-06-22 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchases", "0004_alter_goodsreceipt_receipt_number_and_more"),
        ("stores", "0009_employee_is_manager"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="goodsreceipt",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="goodsreceipt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("purchase_order",),
                name="unique_purchase_order_not_deleted",
            ),
        ),
    ]
