# Generated by Django 5.0.2 on 2025-06-22 08:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_alter_product_base_price_and_more"),
        ("purchases", "0005_alter_goodsreceipt_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="goodsreceiptdetail",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="goodsreceiptdetail",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("goods_receipt", "product_variant"),
                name="unique_goods_receipt_product_not_deleted",
            ),
        ),
    ]
