# Generated by Django 5.0.2 on 2025-07-15 20:16

import apps.content.models.banner
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("title", models.CharField(max_length=255)),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=apps.content.models.banner.banner_image_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg", "gif", "webp"]
                            )
                        ],
                    ),
                ),
                ("link_url", models.CharField(blank=True, max_length=255, null=True)),
                ("alt_text", models.CharField(blank=True, max_length=255, null=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("display_order", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("banner_location", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "banner",
                "ordering": ["-updated_at", "-created_at"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("company_name", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("working_hours", models.TextField(blank=True, null=True)),
                (
                    "facebook_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "instagram_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "youtube_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("tiktok_url", models.CharField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "contactinfo",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="FooterCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(max_length=100)),
                ("display_order", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "footercategory",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="FooterLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("title", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
                ("display_order", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "footerlink",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.CharField(max_length=255, unique=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "featured_image",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_published", models.BooleanField(blank=True, null=True)),
                ("publish_date", models.DateTimeField(blank=True, null=True)),
                ("meta_title", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_description", models.TextField(blank=True, null=True)),
                ("view_count", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "news",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="NewsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("display_order", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "newscategory",
                "managed": True,
            },
        ),
    ]
