# Generated by Django 5.0.2 on 2025-05-29 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_banner_image_url_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'managed': True, 'ordering': ['-updated_at', '-created_at']},
        ),
    ]
