# Generated by Django 5.0.2 on 2025-05-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
